image: docker:19.03.0

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:19.03.0-dind

stages:
  - build
  - publish

build:
  # https://hub.docker.com/_/gradle/tags
  image: gradle:8.1-jdk17
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build
  artifacts:
    when: always
    paths:
      - build/distributions/chatjobparser-1.0-SNAPSHOT.zip
  only:
    - master

publish:
  image: docker:19.03.0
  stage: publish
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/telegram-vacancy-parser:latest .
    - docker push $CI_REGISTRY_IMAGE/telegram-vacancy-parser:latest
  only:
    - master