version: '3.9'

services:

  #DATABASES
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    hostname: postgres
    ports:
      - ${PORT_OUT_POSTGRES}:5432
    env_file:
      - .env
    restart: unless-stopped
    cpus: 1.0
    mem_limit: 1000m

  tomcat:
    image: registry.gitlab.com/pyrinoff/telegram-vacancy-parser/telegram-vacancy-parser:latest
    container_name: springboot
    hostname: springboot
    env_file:
      - .env
    environment:
      database.url: jdbc:postgresql://postgres:5432/jp
      database.user: ${POSTGRES_USER}
      database.password: ${POSTGRES_PASSWORD}
      user.login: ${USER_LOGIN}
      user.password: ${USER_PASSWORD}
      CATALINA_OPTS: "-Xmx2048m"
    ports:
      - ${PORT_OUT_APP}:8080
    depends_on:
      - postgres
    cpus: 1.0
    mem_limit: 3000m

  ouroboros:
    image: pyouroboros/ouroboros
    hostname: ouroboros
    container_name: ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=Europe/Moscow
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default: